name: ci
on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'master'
jobs:
  build:
    runs-on: ubuntu-latest
    environment: test_docker
    steps:
      -
        name: Checkout 
        uses: actions/checkout@v3
      -
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name}}
          push: true
          tags:  ghcr.io/eden-wang/simplewhale:latest
          cache-from: type=registry,ref=eden-wang/simplewhale:buildcache
          cache-to: type=registry,ref=eden-wang/simplewhale:buildcache,mode=max
